# Copyright (C) Free Software Foundation, Inc. All rights reserved.
# Licensed under the AGPL-3.0-only License. See LICENSE in the project root
# for license information.

version: '3.7'
services:
  datasae:
    platform: linux/amd64
    image: registry.digitalservice.id/datasae/datasae:latest
    container_name: datasae
    volumes:
      - ./tests/data/:/app/tests/data/
    working_dir: /app/
    command:
      - --config-name
      - test_local
      - tests/data/config.json
