# Copyright (C) Free Software Foundation, Inc. All rights reserved.
# Licensed under the AGPL-3.0-only License. See LICENSE in the project root
# for license information.

version: '3.7'
services:
  venv:
    build:
      platforms:
        - linux/amd64
      target: venv
      context: .
      cache_from:
        - registry.digitalservice.id/datasae/datasae:venv
    platform: linux/amd64
    image: registry.digitalservice.id/datasae/datasae:venv
  app:
    build:
      platforms:
        - linux/amd64
      target: app
      context: .
      cache_from:
        - registry.digitalservice.id/datasae/datasae:latest
    platform: linux/amd64
    image: registry.digitalservice.id/datasae/datasae:latest
    depends_on:
      - venv
    entrypoint: pip
    command:
      - show
      - datasae
      - --verbose
