# Copyright (C) Free Software Foundation, Inc. All rights reserved.
# Licensed under the AGPL-3.0-only License. See LICENSE in the project root
# for license information.

name: Docker
on:
  push:
    branches:
      - feature/dockerize
  workflow_dispatch:
jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    environment:
      name: docker
      url: https://registry.digitalservice.id/harbor/projects/82/repositories/datasae
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.digitalservice.id
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Build and push venv's image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          target: venv
          context: .
          cache-from: type=registry,ref=registry.digitalservice.id/datasae/datasae:venv
          cache-to: type=inline
          tags: registry.digitalservice.id/datasae/datasae:venv
          push: true
      - name: Build and push app's image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          target: app
          context: .
          cache-from: type=registry,ref=registry.digitalservice.id/datasae/datasae:latest
          cache-to: type=inline
          tags: registry.digitalservice.id/datasae/datasae:latest
          push: true
      - name: Show package info
        run: docker run --platform linux/amd64 --rm --entrypoint pip registry.digitalservice.id/datasae/datasae:latest show datasae --verbose
