# Copyright (C) Free Software Foundation, Inc. All rights reserved.
# Licensed under the AGPL-3.0-only License. See LICENSE in the project root
# for license information.

name: Repository
on: [delete, push]
concurrency:
  group: mirror-repo
  cancel-in-progress: false
jobs:
  mirror:
    name: Mirror Repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirror this repository
        uses: yesolutions/mirror-action@master
        with:
            REMOTE: ${{ secrets.GIT_MIRROR_REPOSITORY_URL }}
            GIT_USERNAME: ${{ secrets.GIT_MIRROR_USERNAME }}
            GIT_PASSWORD: ${{ secrets.GIT_MIRROR_PASSWORD }}
